export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const FILTER_ARTICLES_ID = 'FILTER_ARTICLES_ID'

export const FILTER_ARTICLES_DATE = 'FILTER_ARTICLES_DATE'